{{- if not .Values.persistence.useExistClaim -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: verbacap-data
spec:
  storageClassName: {{ .Values.persistence.newVolume.storageClassName }}
  capacity:
    storage: {{ .Values.persistence.newVolume.capacity }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.persistence.newVolume.persistentVolumeReclaimPolicy }}
  {{- with .Values.persistence.newVolume.driver }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verbacap-data
spec:
  storageClassName: {{ .Values.persistence.newVolume.storageClassName }}
  volumeName: verbacap-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.newVolume.capacity }}
{{- end }}